[project]
name = "approve-opaque-instrument"
authors = ["Anonymous Developer"]
description = "A secure instrument approval and tracking system"
telemetry = false
requirements = []
[contracts.opaque_instrument]
path = "contracts/opaque_instrument.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
